name: Test and Package

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Run eslint
        run: npm run eslint

      - name: Run web-ext lint
        run: npm run web-ext-lint

  firefox:
    name: Package for Firefox
    runs-on: ubuntu-20.04
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Set up for Firefox
        run: npm run prep-firefox

      - name: Build Firefox extension
        run: npx web-ext build

      - name: Sign Firefox extension
        env:
          MOZILLA_API_KEY: ${{ secrets.MOZILLA_API_KEY }}
          MOZILLA_API_SECRET:  ${{ secrets.MOZILLA_API_SECRET }}
        run: npx web-ext sign --api-key $MOZILLA_API_KEY --api-secret $MOZILLA_API_SECRET

      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: aoc_time_logger_firefox
          path: output/aoc_time_logger*-an+fx.xpi
          if-no-files-found: error

  chrome:
    name: Package for Chrome
    runs-on: ubuntu-20.04
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Set up for Chrome
        run: npm run prep-chrome

      - name: Package Chrome extension
        run: ./build-chrome.sh

      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: aoc_time_logger_chrome
          path: output/aoc_time_logger*-chrome.zip
          if-no-files-found: error
